### ISSUE TITLE
Encountering Issues While Replicating Code

### ISSUE THREAD

**Issue by HeBangYan** [cuge1995/SS-attack#1]
Dear author,

Thank you for your generous sharing.

While attempting to reproduce your work, I encountered some issues. Using the SS-3D-Adv attack method, the victim model is PointNet, and the Target Model includes [PointNet, PointNet++, PointConv, DGCNN]. The attack success rates obtained were [89.65, 3.72, 1.92, 3.45], which differ from the results in your paper [94.9, 10.7, 3.96, 7.70]. The hyper-parameters used are those shown in your paper. What's going on? Is there something wrong on my end?

**Comment by cuge1995** [comment]
Dear Hebang,
    Our ASR is different from previous work, pls refer to the AOF attack.

**Comment by HeBangYan** [comment]
Thank you very much for your response. I have used the [inference.py](https://github.com/code-roamer/AOF/blob/master/baselines/inference.py) in AOF, but the experimental results have not changed. What's going on?
